// <auto-generated />
using System;
using EMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412074617_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS.API.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "$2a$11$Oa5Q2WjFBrz3SAeRMRCvBeiSV1m2r.23RSzBLol2SHi3LZ/KQyaq6",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "$2a$11$AqR5.6LGtD3J1CGAXcDOKO.62DCfCle0hdUxYtohodd7tGsSfMI4.",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("EMS.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "priya.sharma@xyz.com",
                            FirstName = "Priya",
                            JoinDate = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sharma",
                            Phone = "9876543210",
                            Salary = 750000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "rahul.patil@xyz.com",
                            FirstName = "Rahul",
                            JoinDate = new DateTime(2021, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Patil",
                            Phone = "9876543211",
                            Salary = 500000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Designation = "Marketing Manager",
                            Email = "sneha.joshi@xyz.com",
                            FirstName = "Sneha",
                            JoinDate = new DateTime(2020, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Joshi",
                            Phone = "9876543212",
                            Salary = 650000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2020, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Designation = "Accountant",
                            Email = "amit.k@xyz.com",
                            FirstName = "Amit",
                            JoinDate = new DateTime(2019, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kulkarni",
                            Phone = "9876543213",
                            Salary = 550000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2019, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Designation = "Operations Manager",
                            Email = "neha.g@xyz.com",
                            FirstName = "Neha",
                            JoinDate = new DateTime(2023, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gupta",
                            Phone = "9876543214",
                            Salary = 600000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2023, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Designation = "Backend Developer",
                            Email = "vikas.y@xyz.com",
                            FirstName = "Vikas",
                            JoinDate = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Yadav",
                            Phone = "9876543215",
                            Salary = 800000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            Designation = "Recruiter",
                            Email = "riya.v@xyz.com",
                            FirstName = "Riya",
                            JoinDate = new DateTime(2021, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Verma",
                            Phone = "9876543216",
                            Salary = 450000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2021, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Designation = "SEO Specialist",
                            Email = "karan.s@xyz.com",
                            FirstName = "Karan",
                            JoinDate = new DateTime(2020, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Singh",
                            Phone = "9876543217",
                            Salary = 520000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2020, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Designation = "Finance Analyst",
                            Email = "anjali.m@xyz.com",
                            FirstName = "Anjali",
                            JoinDate = new DateTime(2019, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mehta",
                            Phone = "9876543218",
                            Salary = 580000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2019, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Designation = "Operations Executive",
                            Email = "rohit.s@xyz.com",
                            FirstName = "Rohit",
                            JoinDate = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shah",
                            Phone = "9876543219",
                            Salary = 480000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Designation = "Frontend Developer",
                            Email = "pooja.n@xyz.com",
                            FirstName = "Pooja",
                            JoinDate = new DateTime(2022, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nair",
                            Phone = "9876543220",
                            Salary = 720000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2022, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Designation = "Content Strategist",
                            Email = "arjun.r@xyz.com",
                            FirstName = "Arjun",
                            JoinDate = new DateTime(2021, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rao",
                            Phone = "9876543221",
                            Salary = 540000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2018, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Designation = "HR Manager",
                            Email = "kavita.i@xyz.com",
                            FirstName = "Kavita",
                            JoinDate = new DateTime(2018, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Iyer",
                            Phone = "9876543222",
                            Salary = 650000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2018, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2017, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Designation = "Senior Accountant",
                            Email = "suresh.p@xyz.com",
                            FirstName = "Suresh",
                            JoinDate = new DateTime(2017, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Pillai",
                            Phone = "9876543223",
                            Salary = 700000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2017, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2020, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Designation = "Logistics Manager",
                            Email = "deepak.c@xyz.com",
                            FirstName = "Deepak",
                            JoinDate = new DateTime(2020, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Chauhan",
                            Phone = "9876543224",
                            Salary = 620000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2020, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
